'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34011.
'
Namespace WSSINALIZA
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ConsultasVeiculosSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ConsultasVeiculos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private authHeaderValueField As AuthHeader
        
        Private ConsultaSinalizaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSinaliza1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSinaliza2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSinaliza3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSinaliza4OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSinaliza5OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSinaliza6OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MalaDireta_v2_0.My.MySettings.Default.MalaDireta_v2_0_WSSINALIZA_ConsultasVeiculos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property AuthHeaderValue() As AuthHeader
            Get
                Return Me.authHeaderValueField
            End Get
            Set
                Me.authHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultaSinalizaCompleted As ConsultaSinalizaCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSinaliza1Completed As ConsultaSinaliza1CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSinaliza2Completed As ConsultaSinaliza2CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSinaliza3Completed As ConsultaSinaliza3CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSinaliza4Completed As ConsultaSinaliza4CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSinaliza5Completed As ConsultaSinaliza5CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSinaliza6Completed As ConsultaSinaliza6CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PesquisaOutrasChaves", RequestElementName:="PesquisaOutrasChaves", RequestNamespace:="http://tempuri.org/", ResponseElementName:="PesquisaOutrasChavesResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strNumCarroceria As String, ByVal strNumCxCambio As String, ByVal strNumEixoTras As String, ByVal strNumTercEixo As String, ByVal strNumMotor As String) As <System.Xml.Serialization.XmlElementAttribute("PesquisaOutrasChavesResult")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza", New Object() {IntIdProduto, strPlaca, strChassi, strNumCarroceria, strNumCxCambio, strNumEixoTras, strNumTercEixo, strNumMotor})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinalizaAsync(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strNumCarroceria As String, ByVal strNumCxCambio As String, ByVal strNumEixoTras As String, ByVal strNumTercEixo As String, ByVal strNumMotor As String)
            Me.ConsultaSinalizaAsync(IntIdProduto, strPlaca, strChassi, strNumCarroceria, strNumCxCambio, strNumEixoTras, strNumTercEixo, strNumMotor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinalizaAsync(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strNumCarroceria As String, ByVal strNumCxCambio As String, ByVal strNumEixoTras As String, ByVal strNumTercEixo As String, ByVal strNumMotor As String, ByVal userState As Object)
            If (Me.ConsultaSinalizaOperationCompleted Is Nothing) Then
                Me.ConsultaSinalizaOperationCompleted = AddressOf Me.OnConsultaSinalizaOperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza", New Object() {IntIdProduto, strPlaca, strChassi, strNumCarroceria, strNumCxCambio, strNumEixoTras, strNumTercEixo, strNumMotor}, Me.ConsultaSinalizaOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinalizaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinalizaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinalizaCompleted(Me, New ConsultaSinalizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.WebMethodAttribute(MessageName:="ConsultaSinaliza1"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pesquisa_Produto_28", RequestElementName:="Pesquisa_Produto_28", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Pesquisa_Produto_28Response", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal strCodOrgAutuador As String, ByVal strNumAutoInfracao As String, ByVal strCodInfracao As String) As <System.Xml.Serialization.XmlElementAttribute("Pesquisa_Produto_28Result")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza1", New Object() {IntIdProduto, strCodOrgAutuador, strNumAutoInfracao, strCodInfracao})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza1Async(ByVal IntIdProduto As Integer, ByVal strCodOrgAutuador As String, ByVal strNumAutoInfracao As String, ByVal strCodInfracao As String)
            Me.ConsultaSinaliza1Async(IntIdProduto, strCodOrgAutuador, strNumAutoInfracao, strCodInfracao, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza1Async(ByVal IntIdProduto As Integer, ByVal strCodOrgAutuador As String, ByVal strNumAutoInfracao As String, ByVal strCodInfracao As String, ByVal userState As Object)
            If (Me.ConsultaSinaliza1OperationCompleted Is Nothing) Then
                Me.ConsultaSinaliza1OperationCompleted = AddressOf Me.OnConsultaSinaliza1OperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza1", New Object() {IntIdProduto, strCodOrgAutuador, strNumAutoInfracao, strCodInfracao}, Me.ConsultaSinaliza1OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinaliza1OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinaliza1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinaliza1Completed(Me, New ConsultaSinaliza1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.WebMethodAttribute(MessageName:="ConsultaSinaliza2"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pesquisa_Produto_25", RequestElementName:="Pesquisa_Produto_25", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Pesquisa_Produto_25Response", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strUF As String, ByVal DtInicio As Date, ByVal DtFim As Date, ByVal IntIndicador As Integer) As <System.Xml.Serialization.XmlElementAttribute("Pesquisa_Produto_25Result")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza2", New Object() {IntIdProduto, strPlaca, strUF, DtInicio, DtFim, IntIndicador})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza2Async(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strUF As String, ByVal DtInicio As Date, ByVal DtFim As Date, ByVal IntIndicador As Integer)
            Me.ConsultaSinaliza2Async(IntIdProduto, strPlaca, strUF, DtInicio, DtFim, IntIndicador, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza2Async(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strUF As String, ByVal DtInicio As Date, ByVal DtFim As Date, ByVal IntIndicador As Integer, ByVal userState As Object)
            If (Me.ConsultaSinaliza2OperationCompleted Is Nothing) Then
                Me.ConsultaSinaliza2OperationCompleted = AddressOf Me.OnConsultaSinaliza2OperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza2", New Object() {IntIdProduto, strPlaca, strUF, DtInicio, DtFim, IntIndicador}, Me.ConsultaSinaliza2OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinaliza2OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinaliza2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinaliza2Completed(Me, New ConsultaSinaliza2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.WebMethodAttribute(MessageName:="ConsultaSinaliza3"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pesquisa_Produto_27", RequestElementName:="Pesquisa_Produto_27", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Pesquisa_Produto_27Response", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal intTipoDocto As Integer, ByVal strDocumento As String) As <System.Xml.Serialization.XmlElementAttribute("Pesquisa_Produto_27Result")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza3", New Object() {IntIdProduto, intTipoDocto, strDocumento})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza3Async(ByVal IntIdProduto As Integer, ByVal intTipoDocto As Integer, ByVal strDocumento As String)
            Me.ConsultaSinaliza3Async(IntIdProduto, intTipoDocto, strDocumento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza3Async(ByVal IntIdProduto As Integer, ByVal intTipoDocto As Integer, ByVal strDocumento As String, ByVal userState As Object)
            If (Me.ConsultaSinaliza3OperationCompleted Is Nothing) Then
                Me.ConsultaSinaliza3OperationCompleted = AddressOf Me.OnConsultaSinaliza3OperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza3", New Object() {IntIdProduto, intTipoDocto, strDocumento}, Me.ConsultaSinaliza3OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinaliza3OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinaliza3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinaliza3Completed(Me, New ConsultaSinaliza3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.WebMethodAttribute(MessageName:="ConsultaSinaliza4"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pesquisa_Produto_23", RequestElementName:="Pesquisa_Produto_23", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Pesquisa_Produto_23Response", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strNumMotor As String, ByVal strRenavam As String) As <System.Xml.Serialization.XmlElementAttribute("Pesquisa_Produto_23Result")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza4", New Object() {IntIdProduto, strPlaca, strChassi, strNumMotor, strRenavam})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza4Async(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strNumMotor As String, ByVal strRenavam As String)
            Me.ConsultaSinaliza4Async(IntIdProduto, strPlaca, strChassi, strNumMotor, strRenavam, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza4Async(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strNumMotor As String, ByVal strRenavam As String, ByVal userState As Object)
            If (Me.ConsultaSinaliza4OperationCompleted Is Nothing) Then
                Me.ConsultaSinaliza4OperationCompleted = AddressOf Me.OnConsultaSinaliza4OperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza4", New Object() {IntIdProduto, strPlaca, strChassi, strNumMotor, strRenavam}, Me.ConsultaSinaliza4OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinaliza4OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinaliza4CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinaliza4Completed(Me, New ConsultaSinaliza4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.WebMethodAttribute(MessageName:="ConsultaSinaliza5"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pesquisa_Produto_24", RequestElementName:="Pesquisa_Produto_24", RequestNamespace:="http://tempuri.org/", ResponseElementName:="Pesquisa_Produto_24Response", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal strChassi As String, ByVal intTipoBlq As Integer) As <System.Xml.Serialization.XmlElementAttribute("Pesquisa_Produto_24Result")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza5", New Object() {IntIdProduto, strChassi, intTipoBlq})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza5Async(ByVal IntIdProduto As Integer, ByVal strChassi As String, ByVal intTipoBlq As Integer)
            Me.ConsultaSinaliza5Async(IntIdProduto, strChassi, intTipoBlq, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza5Async(ByVal IntIdProduto As Integer, ByVal strChassi As String, ByVal intTipoBlq As Integer, ByVal userState As Object)
            If (Me.ConsultaSinaliza5OperationCompleted Is Nothing) Then
                Me.ConsultaSinaliza5OperationCompleted = AddressOf Me.OnConsultaSinaliza5OperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza5", New Object() {IntIdProduto, strChassi, intTipoBlq}, Me.ConsultaSinaliza5OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinaliza5OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinaliza5CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinaliza5Completed(Me, New ConsultaSinaliza5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.WebMethodAttribute(MessageName:="ConsultaSinaliza6"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaSinaliza", RequestElementName:="ConsultaSinaliza", RequestNamespace:="http://tempuri.org/", ResponseElementName:="ConsultaSinalizaResponse", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Overloads Function ConsultaSinaliza(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strUF As String, ByVal intCodMunic As Integer) As <System.Xml.Serialization.XmlElementAttribute("ConsultaSinalizaResult")> String
            Dim results() As Object = Me.Invoke("ConsultaSinaliza6", New Object() {IntIdProduto, strPlaca, strChassi, strUF, intCodMunic})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza6Async(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strUF As String, ByVal intCodMunic As Integer)
            Me.ConsultaSinaliza6Async(IntIdProduto, strPlaca, strChassi, strUF, intCodMunic, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSinaliza6Async(ByVal IntIdProduto As Integer, ByVal strPlaca As String, ByVal strChassi As String, ByVal strUF As String, ByVal intCodMunic As Integer, ByVal userState As Object)
            If (Me.ConsultaSinaliza6OperationCompleted Is Nothing) Then
                Me.ConsultaSinaliza6OperationCompleted = AddressOf Me.OnConsultaSinaliza6OperationCompleted
            End If
            Me.InvokeAsync("ConsultaSinaliza6", New Object() {IntIdProduto, strPlaca, strChassi, strUF, intCodMunic}, Me.ConsultaSinaliza6OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSinaliza6OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSinaliza6CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSinaliza6Completed(Me, New ConsultaSinaliza6CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/", IsNullable:=false)>  _
    Partial Public Class AuthHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usuarioField As String
        
        Private senhaField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Senha() As String
            Get
                Return Me.senhaField
            End Get
            Set
                Me.senhaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinalizaCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinalizaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinalizaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinaliza1CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinaliza1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinaliza1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinaliza2CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinaliza2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinaliza2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinaliza3CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinaliza3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinaliza3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinaliza4CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinaliza4CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinaliza4CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinaliza5CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinaliza5CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinaliza5CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub ConsultaSinaliza6CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSinaliza6CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSinaliza6CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
